# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevtrial5',
                'doc_host': 'https://Ber1812.github.io',
                'git_url': 'https://github.com/Ber1812/nbdevtrial5',
                'lib_path': 'nbdevtrial5'},
  'syms': { 'nbdevtrial5.core': {'nbdevtrial5.core.foo': ('core.html#foo', 'nbdevtrial5/core.py')},
            'nbdevtrial5.first_module': { 'nbdevtrial5.first_module.can_you_count': ( 'first_module.html#can_you_count',
                                                                                      'nbdevtrial5/first_module.py')}}}