# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_first_module.ipynb.

# %% auto 0
__all__ = ['can_you_count']

# %% ../nbs/00_first_module.ipynb 3
def can_you_count(answer):
    "what is two plus two?"
    return f'It is {answer}'
